apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app-service
spec:
  selector:
    app: tech-challenge-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
