apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tech-challenge-db-storage-class
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
