apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-db
  template:
    metadata:
      labels:
        app: tech-challenge-db
    spec:
      containers:
      - name: tech-challenge-db-container
        image: perinzaum/modulo2-database
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: tech-challenge-db-container
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: tech-challenge-db-container
        persistentVolumeClaim:
          claimName: tech-challenge-db-persistent-volume-claim
