apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-db-service
spec:
  selector:
    app: tech-challenge-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
