apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-app
  template:
    metadata:
      labels:
        app: tech-challenge-app
    spec:
      containers:
      - name: tech-challenge-app-container
        image: perinzaum/modulo2-tech-challenge
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: tech-challenge-app-config
              key: ENVIRONMENT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: tech-challenge-app-config
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 8000
